### PR TITLE
reduce_angs_with_amplitude flag according to amplitude

### PR DESCRIPTION
**Pull request by skostogl**
continuation of [pull request](https://github.com/amereghe/SixDesk/pull/12), starting from proper base branch.

### CODE REVIEW

**Comment by amereghe** [comment]
Hello Sofia,
many many thanks for the pull request. In the following, some comments from my side:

-- utilities/bash/set_env.sh
* I guess that if the user has not at all defined the variable reduce_angs_with_amplitude, the code breask somewhere. Have you tried this case?
* I would keep a block like:
if [ -z "${reduce_angs_with_aplitude}" ] ; then
    sixdeskmess -1 "wrong spelling of reduce_angs_with_amplitude. Please correct it for future use"
    reduce_angs_with_aplitude=${reduce_angs_with_amplitude}
fi
* please keep lReduceAngsWithAmplitude as a boolean (true/false). In this way, we minimise the time to check if this functionality should be used or not. Moreover, if the user has not defined the reduce_angs_with_amplitude, export it with value 0, so that the initialisation is properly done;
* I would mv in this function the checks (done in dot_profile) 
if [ ${__kmin} -ne 1 ] || [ ${__kend} -ne ${__kmax} ] || [ ${__kstep} -ne 1 ] ; then
    sixdeskmess -1 "reduced angles with amplitudes available only for kmin=1, kend=kmax and kstep=1"
    # disable functionality
    export reduce_angs_with_amplitude=0
    export lreduce_angs_with_amplitude=false
fi
if (( $(echo "${__lReduceAngsWithAmplitude} >= ${ampfinish}"|bc -l) )) ; then
    sixdeskmess -1 "reduced angles with amplitudes flag greater than maximum amplitude, flag de-activated"
fi
Since it is in this point where we set the env vars, including sanity checks on their value;

-- utilities/bash/dot_profile
* for better coding, please initialise also KKs_ampl together with the other vars:
KKs_ampl="0"
* (just a reminder to mv the two aforementioned checks in set_env.sh :D )
* the following staement:
if (( $(echo "${__lReduceAngsWithAmplitude} > 0 "|bc -l) )) ; then 
should become
if ${lreduce_angs_with_amplitude} ; then
* I would not fill KKs_angle with n times iAmpli, but only with nTotAngles once the following loop is finished:
for (( kk=1; kk<=${__angles_nb}; kk++ )) ; do
where nTotAngles is defined as:
let nTotAngles+=${__angles_nb}
In case the functionality is not triggered, then I would add only ${__kend} to KKs;

-- run_six.sh
* if you follow my suggestions, then we can forget about all the code between:
sixdeskmess -1 "Considering amplitude step: $Ampl"
and
for (( iAngle=0; iAngle<${#kksLoop[@]}; iAngle++ )) ; do
we would need just to add:
let jAmple=${iAmple}+1
and rewrite the following for loop as:
for (( iAngle=${KKs_ampl[${iAmple}]}; iAngle<${KKs_ampl[${jAmple}]}; iAngle++ )) ; do
   	    kk=${KKs[${iAngle}]}
	    Angle=${Angles[${iAngle}]}
	    kang=${kAngs[${iAngle}]}
* could you restore:
trap "printSummary; sixdeskexit  2" SIGQUIT
I guess you changed it by mistake with
trap "printSummary; sixdeskeedt  2" SIGQUIT
* could you also restore the missing comment:
# generate array of angles (it returns KKs, Angles and kAngs, and reduced ones)
before
sixdeskAllAngles $kinil $kendl $kmaxl $kstep $ampstart $ampfinish $lbackcomp ${lReduceAngsWithAmplitude} ${totAngle} ${ampFactor}

Finally, I just committed a bug fix in isolateScripts. So, could you:
1. merge this last bug fix onto your branch;
2. apply my suggestions;
3. update the pull request;

Thanks a lot!
Cheers,
A.

**Comment by skostogl** [comment]
Yes you are right, if the is not defined the code breaks. Now, if it is not defined it is automatically set to zero.

Ok lReduceAngsWithAmplitude stays boolean.

Now in set_env.sh the checks are:

- If the flag is mispelled, the value is passed to the correct variable
- If it is not defined it is set to zero
- If it is set and it has a positive value:
  -Check if the simulation is long
  -Check that kinil=1, kendl=kmax, kstep=1
  -If set to a greater value than max amplitude, the flag is deactivated

in dot_profile:

All values of nTotAngles are appended to KKs_ampl. If flag is off only __kend is added.

in run_six.sh:

if the flag is on it uses two consecutive values of KKs_ampl as an index for the angles, while if the flag is off KKs_ampl will include only two values and jample is initialised to 0.

**Comment by amereghe** [comment]
Hello Sofia,
many thanks for the changes! As you can see, I have made few others (really minor ones).
I will test this version of the script against some tests of mine, and then will merge.
Ciao!

**Comment by skostogl** [comment]
Thanks Alessio!

**Pull request merged**
